### PR TITLE
fix #1

### LINKED ISSUE #1: I broke it :(
In the process of converting this script to Joomla and supporting language files I have broken the functionality of the "Clear Completed" button.

It worked perfectly outside of joomla https://codepen.io/brianteeman/pen/RwJopqV

I just can't see what is different to produce the error
```
admin-tasklist.js?ece6dd409db6ff4965a740b51c4cc8e5:38 Uncaught ReferenceError: deleteIndexes is not defined
    at HTMLButtonElement.
```

@dgrammatiko any suggestion?

### PR DESCRIPTION
**Pull request by dgrammatiko**

### CODE REVIEW

**Comment by brianteeman** [comment]
thanks - how did I miss that

**Comment by dgrammatiko** [comment]
NP, you should consider using https://www.npmjs.com/package/idb-keyval to persist the data in a real storage (a database is provided for free on all the evergreen browsers). Also it should be an easy task (import the lib `import { get, set } from 'idb-keyval';` and replace the `localstorage.get`,  `localstorage.set` with just `get`, `set`)

**Comment by brianteeman** [comment]
I dont see the benefit. What am I missing?

**Comment by dgrammatiko** [comment]
Localstorage is ephemeral (safari is 7days, other browsers have other heuristics/timelines). The IDB is actual storage that is not going to go away unless the user decides to clear it...

**Comment by brianteeman** [comment]
>  The IDB is actual storage that is not going to go away unless the user decides to clear it...

That is the same for chrome. Dont care about any other browser as thats all I use :)

**Comment by brianteeman** [comment]
but when I get a chance I may take a look

**Pull request merged**
